default_context:
    repo_name: "advanced_uv_repo"
    project_name: "project_name"
    project_structure: "advanced"
    author_name: "author_name"
    description: "description"
    python_version: "3.12"
    open_source_license: "MIT"
