default_context:
    repo_name: "advance_uv_repo"
    project_name: "project_name"
    project_structure: "advance"
    author_name: "author_name"
    description: "description"
    python_version: "3.12"
    open_source_license: "MIT"
