# Main configuration file for the project
defaults:
  - model_conf
  - training_conf
  - optimizer: adam
  - _self_

wandb:
  enabled: true

# Define which parts of config to use
use_model_conf: true
use_training_conf: true
