name: Check Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    name: Template generation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_structure: ["simple", "advanced"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Execute template
        run: |
          uv run invoke template \
            --project-structure=${{ matrix.project_structure }}

      - name: Generated tree structure
        run: |
          tree -a ${{ matrix.project_structure }}_uv_repo

      - name: Upload generated template
        uses: actions/upload-artifact@v4
        with:
          name: generated-template-${{ matrix.project_structure }}
          path: ${{ matrix.project_structure }}_uv_repo
          include-hidden-files: true

  uv-project:
    name: Project using uv
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_structure: ["simple", "advanced"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Download generated template
        uses: actions/download-artifact@v4
        with:
          name: generated-template-${{ matrix.project_structure }}
          path: ${{ matrix.project_structure }}

      - name: Artifact structure
        run: |
          tree -a ${{ matrix.project_structure }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        run: |
          cd ${{ matrix.project_structure }}
          uv sync --all-extras --dev

      - name: List all project commands
        run: |
          cd ${{ matrix.project_structure }}
          uv run invoke --list

      - name: Run project commands
        run: |
          cd ${{ matrix.project_structure }}
          uv run invoke preprocess-data
          uv run invoke train
          uv run invoke test
        env:
          TERM: xterm

      - name: Build documentation
        if: ${{ matrix.project_structure == 'advanced' }}
        run: |
          cd ${{ matrix.project_structure }}
          uv run invoke build-docs
        env:
          TERM: xterm

      - name: Build dockerfiles
        if: ${{ matrix.project_structure == 'advanced' }}
        run: |
          cd ${{ matrix.project_structure }}
          ls -R
          uv run invoke docker-build
        env:
          TERM: xterm

      - name: Check devcontainer
        if: ${{ matrix.project_structure == 'advanced' }}
        run: |
          cd ${{ matrix.project_structure }}
          npx @devcontainers/cli build --workspace-folder .
          npx @devcontainers/cli up --workspace-folder .
        env:
          TERM: xterm
